### ISSUE TITLE
Look into recording Discord meetings

### ISSUE THREAD

**Issue by napkinbrown** [kapravel/hackpack-web#19]
Check out OBS-Discord integration

Should be able to:
- Record meetings and upload them to Youtube
- Record shared screen + audio, host's voice, and attendees' voices
-  (Nice to have) Include Discord text channel messages (I believe OBS-Discord integration handles this)

**Comment by John123Allison** [comment]
https://www.obs.live/articles/2019/5/14/how-to-capture-discord-audio-with-obs

**Comment by napkinbrown** [comment]
For future use:
https://streamkit.discord.com/overlay
